name: valkki_orival
description: Välkki-Örival Conlang App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 # share_plus: ^13.1.0   # for TXT generation

flutter:
  uses-material-design: true
  assets:
    - assets/data/